---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'ui'
    static_configs:
      - targets:
        - 'ui:9292'

  - job_name: 'comment'
    static_configs:
      - targets:
        - 'comment:9292'

  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'

  - job_name: 'mongodb'
    static_configs:
      - targets:
        - 'mongodb-exporter:9216'

  #- job_name: 'blackbox'
  #  metrics_path: /probe
  #  params:
  #    module: ['http_2xx']
  #  static_configs:
  #    - targets:
  #      - 'http://post'
  #      - 'http://ui'
  #      - 'http://comment'
  #      - 'https://ya.ru'
  #  relabel_configs:
  #    - source_labels: [__address__]
  #      target_label: __param_target
  #    - source_labels: [__param_target]
  #      target_label: instance
  #    - target_label: __address__
  #      replacement: blackbox_exporter:9115 # The blackbox exporter's real hostname:port
  - job_name: 'blackbox-exporter'
    metrics_path: /metrics
    params:
      module: ['http_2xx_example']
    static_configs:
      - targets:
        - 'http://post:5000/metrics'
        - 'http://comment:9292/metrics'
        - 'http://ui:9292/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
